---
title: "Course Project 1"
author: "Genevieve Dupuis"
date: "April 28, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(dplyr)
```
## Loading and pre-processing the data
```{r}
	# Read in raw data, located in working directory (set working directory if necessary)
    wd <- "C:/Coursera/5. Reproducible Research/Week2"
    data <- read.csv(paste0(wd,"/activity.csv"),na.strings = "NA",colClasses = c("numeric","factor","integer"))

	# Set type for "date" as Date (done here to define format)
    data$date <- as.Date(data$date, "%Y-%m-%d")
```
## Mean total number of steps taken per day
```{r}
	# Calculate total steps per day  
    total <- tapply(data$steps,data$date,sum, na.rm = TRUE)
    print(total)

	# Make histogram of total steps per day
    hist(total, ylab = "Number of days", xlab = "Number of steps", 
         main = "Histogram of total number of steps per day")

	# Calculate mean number of steps per day (ignoring missing)
		mean <- mean(total[!is.na(total)])
		print(mean)
	
	# Calculate median number of steps per day (ignoring missing)
		median <- median(total[!is.na(total)])
		print(median)
```
## Average daily activity pattern
```{r}
	# Make time-series plot of 5-minute interval vs. average steps taken
		# Calculate mean steps per interval, then plot
		interv <- tapply(data$steps,data$interval,mean, na.rm = TRUE)
		plot(names(interv),interv, type = "l", xlab = "5-minute interval", ylab = "Average number of steps", 
		     main = "Time-series of average steps per 5 minute interval")
	
	# Determine which five-minute interval has max average steps 
		interv_max <- max(interv)
		print(names(interv[interv == interv_max]))
```
## Imputing missing values
```{r}
	# Calculate total number of missing values
		sum(is.na(data))
```
### Strategy for imputation: Create new dataset that includes the mean of the 5-minute interval for all days assigned to any missing values
```{r}
    # Create data set that contains values for imputing (mean value per 5-minute interval)
    impute <- cbind(interval = names(interv),mean = interv)
    # for each row in data set
    for (i in 1:dim(data)[1]) { 		
      # if steps is missing (there are no missings in date or interval)
      if ( is.na(data[i,1]) ) { 		
        # set interval for missing observation
        NAint <- data$interval[i]		
        # assign second column of impute (mean for that interval) to the missing value
        data[i,1] <- as.numeric(impute[which(impute[,1] == NAint),2]) 
      }		
    }
	
	# Make histogram of imputed data, calculate mean/median
		# Histogram
		total_imp <- tapply(data$steps,data$date,sum)
		hist(total_imp, ylab = "Number of days", xlab = "Number of steps", 
		     main = "Histogram of total number of steps per day (with imputation)")
	
		# Calculate mean number of steps per day (with imputed data)
		mean_imp <- mean(total_imp)
		print(mean_imp)
	
		# Calculate median number of steps per day (with imputed data) 
		median_imp <- median(total_imp)
		print(median_imp)
```

## Differences in activity between weekdays and weekends
```{r}
	# Add column to data set with weekday/weekend ( 0 = weekday, 1 = weekend )
		data <- mutate(data,day = weekdays(date), daygroup = as.integer(day %in% c("Friday","Saturday")))
		data$daygroup[data$daygroup == "1"] <- "weekend"
		data$daygroup[data$daygroup == "0"] <- "weekday"
	
	# Make time-series plot comparing weekend and weekday
		# Make data set for weekend and weekday, apply mean per 5-minute interval
		data_we <- filter(data,daygroup == "weekend")
		data_wd <- filter(data,daygroup == "weekday")
		interv_we <- tapply(data_we$steps,data_we$interval,mean)
		interv_wd <- tapply(data_wd$steps,data_wd$interval,mean)
```
```{r, fig.width=10, fig.height=10}
		# Plot the two data sets!
		par(mfrow=c(2,1))
		plot(names(interv_we),interv_we, type = "l", xlab = "5-minute interval", 
		     ylab = "Average number of steps", main = "Weekends")
		plot(names(interv_wd),interv_wd, type = "l", xlab = "5-minute interval", 
		     ylab = "Average number of steps", main = "Weekdays")
```		




